/**
 * Complete questionnaire data extracted from the Excel file.
 * All 10 categories with 97 total questions.
 */

export const SERVICES = [
  { name: 'front_office', display_name: 'Front Office' },
  { name: 'housekeeping', display_name: 'Housekeeping' },
  { name: 'fnb_outlets', display_name: 'F&B Outlets' },
  { name: 'kitchen', display_name: 'Kitchen / Food Production' },
  { name: 'facilities', display_name: 'Facilities & Amenities' },
  { name: 'special_assistance', display_name: 'Special Assistance Services' },
  { name: 'banquet_events', display_name: 'Banquet / Event Services' },
  { name: 'pool_gym', display_name: 'Pool / Gym Membership' },
];

export const CATEGORIES = [
  { slug: 'guest_categorization', name: 'Guest Categorization', sort_order: 1, service: null },
  { slug: 'front_office', name: 'Front Office', sort_order: 2, service: 'front_office' },
  { slug: 'housekeeping', name: 'Housekeeping', sort_order: 3, service: 'housekeeping' },
  { slug: 'fnb_outlets', name: 'F&B Outlets', sort_order: 4, service: 'fnb_outlets' },
  { slug: 'kitchen', name: 'Kitchen / Food Production', sort_order: 5, service: 'kitchen' },
  { slug: 'facilities', name: 'Facilities & Amenities', sort_order: 6, service: 'facilities' },
  { slug: 'special_assistance', name: 'Special Assistance Services', sort_order: 7, service: 'special_assistance' },
  { slug: 'banquet_events', name: 'Banquet / Event Guests', sort_order: 8, service: 'banquet_events' },
  { slug: 'pool_gym', name: 'Pool / Gym Members', sort_order: 9, service: 'pool_gym' },
  { slug: 'final_experience', name: 'Final Experience & Insights', sort_order: 10, service: null },
];

export const QUESTIONS = {
  guest_categorization: [
    { sr: 1, text: 'What best describes your visit?', options: ['Staying Guest', 'Restaurant/Dining Guest', 'Banquet/Event Guest', 'Pool/Gym Member', 'Visitor/Other'] },
    { sr: 2, text: 'Purpose of visit:', options: ['Business', 'Leisure', 'Event/Function', 'Dining Only'] },
    { sr: 3, text: 'Duration of stay/service usage:', options: ['Few Hours', '1 Day', '2–3 Days', 'More than 3 Days'] },
  ],
  front_office: [
    { sr: 1, text: 'How was your check-in/check-out experience?', options: ['Very Smooth', 'Smooth', 'Average', 'Poor'] },
    { sr: 2, text: 'Waiting time at reception:', options: ['Very Short', 'Short', 'Moderate', 'Long'] },
    { sr: 3, text: 'Staff greeting and welcome experience:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 4, text: 'Did staff explain hotel facilities clearly?', options: ['Yes', 'Partially', 'No'] },
    { sr: 5, text: 'How professional was front desk staff?', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 6, text: 'Handling of special requests (early check-in etc.):', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 7, text: 'How well were your queries handled?', options: ['Fully Resolved', 'Partially', 'Not Resolved'] },
    { sr: 8, text: 'Communication skills of staff:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 9, text: 'Billing process transparency:', options: ['Very Clear', 'Clear', 'Confusing', 'Poor'] },
    { sr: 10, text: 'Speed of check-out process:', options: ['Very Fast', 'Fast', 'Average', 'Slow'] },
    { sr: 11, text: 'Overall front office experience:', options: ['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied'] },
  ],
  housekeeping: [
    { sr: 1, text: 'Cleanliness of room on arrival:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 2, text: 'Cleanliness of bathroom:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 3, text: 'Quality of bed linen & duvet:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 4, text: 'Freshness of towels and linen:', options: ['Very Fresh', 'Fresh', 'Average', 'Poor'] },
    { sr: 5, text: 'Availability of bathroom amenities:', options: ['Fully Available', 'Partial', 'Not Available'] },
    { sr: 6, text: 'Quality of toiletries (soap, shampoo):', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 7, text: 'Room fragrance and hygiene:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 8, text: 'Housekeeping response time:', options: ['Very Fast', 'Fast', 'Average', 'Slow'] },
    { sr: 9, text: 'Frequency of room cleaning:', options: ['Very Satisfactory', 'Satisfactory', 'Less', 'Poor'] },
    { sr: 10, text: 'Maintenance issues in room:', options: ['None', 'Minor', 'Major'] },
    { sr: 11, text: 'How quickly were issues resolved?', options: ['Immediately', 'Few Hours', 'Delayed', 'Not Resolved'] },
    { sr: 12, text: 'Cleanliness of corridors & public areas:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 13, text: 'Overall housekeeping satisfaction:', options: ['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied'] },
  ],
  fnb_outlets: [
    { sr: 1, text: 'Restaurant ambiance:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 2, text: 'Staff behavior in restaurant:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 3, text: 'Service speed in restaurant:', options: ['Very Fast', 'Fast', 'Average', 'Slow'] },
    { sr: 4, text: 'Cleanliness of dining area:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 5, text: 'Menu variety:', options: ['Excellent', 'Good', 'Average', 'Limited'] },
    { sr: 6, text: 'Taste of food:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 7, text: 'Food presentation:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 8, text: 'Value for money in restaurant:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 9, text: 'Did you use In-Room Dining (IRD)?', options: ['Yes', 'No'] },
    { sr: 10, text: 'IRD menu clarity:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 11, text: 'IRD delivery time:', options: ['Very Fast', 'Fast', 'Average', 'Slow'] },
    { sr: 12, text: 'Food quality (IRD):', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 13, text: 'Temperature of food delivered:', options: ['Perfect', 'Acceptable', 'Not Satisfactory'] },
    { sr: 14, text: 'Overall F&B satisfaction:', options: ['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied'] },
  ],
  kitchen: [
    { sr: 1, text: 'Consistency in food taste:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 2, text: 'Food hygiene standards:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 3, text: 'Freshness of ingredients:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 4, text: 'Portion size satisfaction:', options: ['Excellent', 'Good', 'Average', 'Small'] },
    { sr: 5, text: 'Variety of cuisine options:', options: ['Excellent', 'Good', 'Average', 'Limited'] },
    { sr: 6, text: 'Special dietary needs handling:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 7, text: 'Overall kitchen quality perception:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
  ],
  facilities: [
    { sr: 1, text: 'Wi-Fi quality:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 2, text: 'Parking facility:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 3, text: 'Elevator availability & condition:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 4, text: 'Swimming pool cleanliness & maintenance:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 5, text: 'Gym facility quality:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 6, text: 'Availability of recreational facilities:', options: ['Excellent', 'Good', 'Average', 'Limited'] },
    { sr: 7, text: 'Safety & security measures:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 8, text: 'Ease of accessing hotel facilities:', options: ['Very Easy', 'Easy', 'Average', 'Difficult'] },
    { sr: 9, text: 'Digital services (online check-in, etc.):', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 10, text: 'Maintenance of overall property:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 11, text: 'Overall facilities satisfaction:', options: ['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied'] },
  ],
  special_assistance: [
    { sr: 1, text: 'Did you require any special assistance during your visit?', options: ['Yes', 'No'] },
    { sr: 2, text: 'What type of assistance did you require?', options: ['Wheelchair access', 'Elderly assistance', 'Medical support', 'Luggage assistance', 'None'] },
    { sr: 3, text: 'Was the required assistance easily available?', options: ['Easily Available', 'Available with Delay', 'Not Available'] },
    { sr: 4, text: 'How would you rate the staff support for special assistance?', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 5, text: 'Was the staff trained to handle special assistance needs?', options: ['Well Trained', 'Moderately Trained', 'Poorly Trained'] },
    { sr: 6, text: 'Availability of accessibility features (ramps, lifts, etc.):', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 7, text: 'Ease of movement within hotel for special needs:', options: ['Very Easy', 'Easy', 'Difficult', 'Very Difficult'] },
    { sr: 8, text: 'Overall satisfaction with special assistance services:', options: ['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied'] },
    { sr: 9, text: 'What could be improved in special assistance services?', options: ['Faster response', 'Better facilities', 'More trained staff', 'No improvement needed'] },
  ],
  banquet_events: [
    { sr: 1, text: 'What type of event did you attend?', options: ['Wedding', 'Corporate Event', 'Conference', 'Social Function'] },
    { sr: 2, text: 'How would you rate banquet hall ambiance?', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 3, text: 'Seating arrangement and comfort:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 4, text: 'Cleanliness of banquet area:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 5, text: 'Staff support during event:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 6, text: 'Promptness of service during event:', options: ['Very Fast', 'Fast', 'Average', 'Slow'] },
    { sr: 7, text: 'Food quality at event:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 8, text: 'Variety of food options:', options: ['Excellent', 'Good', 'Average', 'Limited'] },
    { sr: 9, text: 'Food service efficiency:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 10, text: 'Parking arrangement for event:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 11, text: 'Crowd management:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 12, text: 'Overall banquet/event satisfaction:', options: ['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied'] },
  ],
  pool_gym: [
    { sr: 1, text: 'Which facility do you use?', options: ['Swimming Pool', 'Gym', 'Both'] },
    { sr: 2, text: 'Frequency of usage:', options: ['Daily', 'Weekly', 'Occasionally'] },
    { sr: 3, text: 'Cleanliness of pool/gym:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 4, text: 'Maintenance of equipment:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 5, text: 'Availability of equipment/resources:', options: ['Always Available', 'Mostly Available', 'Limited'] },
    { sr: 6, text: 'Staff assistance in gym/pool area:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 7, text: 'Trainer/instructor support (if applicable):', options: ['Excellent', 'Good', 'Average', 'Not Available'] },
    { sr: 8, text: 'Safety measures (lifeguard, instructions, etc.):', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 9, text: 'Changing rooms & locker facilities:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 10, text: 'Overall satisfaction with facility:', options: ['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied'] },
    { sr: 11, text: 'What should be improved?', options: ['Cleanliness', 'Equipment', 'Staff support', 'No improvement needed'] },
  ],
  final_experience: [
    { sr: 1, text: 'What did you like the most?', options: ['Service', 'Cleanliness', 'Food', 'Facilities'] },
    { sr: 2, text: 'What did you dislike the most?', options: ['Service', 'Cleanliness', 'Food', 'Facilities', 'None'] },
    { sr: 3, text: 'Did the hotel meet your expectations?', options: ['Fully', 'Partially', 'Not at all'] },
    { sr: 4, text: 'Value for money:', options: ['Excellent', 'Good', 'Average', 'Poor'] },
    { sr: 5, text: 'Likelihood to revisit:', options: ['Definitely', 'Probably', 'Not Sure', 'No'] },
    { sr: 6, text: 'Likelihood to recommend:', options: ['Definitely', 'Probably', 'Not Sure', 'No'] },
  ],
};

// Demo data for testing without Supabase
export const DEMO_BILLS = [
  {
    id: 'bill-001',
    bill_number: 'BILL-2026-001',
    customer_name: 'Rahul Sharma',
    room_number: '301',
    check_in_date: '2026-04-15',
    check_out_date: '2026-04-18',
    is_feedback_submitted: false,
    services: ['front_office', 'housekeeping', 'fnb_outlets', 'kitchen', 'facilities'],
  },
  {
    id: 'bill-002',
    bill_number: 'BILL-2026-002',
    customer_name: 'Priya Patel',
    room_number: null,
    check_in_date: '2026-04-17',
    check_out_date: '2026-04-17',
    is_feedback_submitted: false,
    services: ['fnb_outlets', 'kitchen'],
  },
  {
    id: 'bill-003',
    bill_number: 'BILL-2026-003',
    customer_name: 'Amit Singh',
    room_number: null,
    check_in_date: '2026-04-16',
    check_out_date: '2026-04-16',
    is_feedback_submitted: false,
    services: ['banquet_events'],
  },
  {
    id: 'bill-004',
    bill_number: 'BILL-2026-004',
    customer_name: 'Sneha Reddy',
    room_number: '505',
    check_in_date: '2026-04-10',
    check_out_date: '2026-04-14',
    is_feedback_submitted: true,
    services: ['front_office', 'housekeeping', 'fnb_outlets', 'kitchen', 'facilities', 'pool_gym', 'special_assistance'],
  },
  {
    id: 'bill-005',
    bill_number: 'BILL-2026-005',
    customer_name: 'Vikram Joshi',
    room_number: null,
    check_in_date: '2026-04-18',
    check_out_date: '2026-04-18',
    is_feedback_submitted: false,
    services: ['pool_gym'],
  },
];

// Demo submitted responses for admin dashboard
export const DEMO_RESPONSES = [
  {
    id: 'resp-001',
    bill_number: 'BILL-2026-004',
    customer_name: 'Sneha Reddy',
    guest_type: 'Staying Guest',
    visit_purpose: 'Leisure',
    stay_duration: 'More than 3 Days',
    submitted_at: '2026-04-14T14:30:00Z',
    services: ['front_office', 'housekeeping', 'fnb_outlets', 'kitchen', 'facilities', 'pool_gym', 'special_assistance'],
    answers: {
      front_office: { avg: 3.6, answers: { 1: 'Very Smooth', 2: 'Short', 3: 'Excellent', 4: 'Yes', 5: 'Excellent', 6: 'Good', 7: 'Fully Resolved', 8: 'Excellent', 9: 'Very Clear', 10: 'Fast', 11: 'Very Satisfied' } },
      housekeeping: { avg: 3.2, answers: { 1: 'Good', 2: 'Excellent', 3: 'Good', 4: 'Fresh', 5: 'Fully Available', 6: 'Good', 7: 'Good', 8: 'Fast', 9: 'Satisfactory', 10: 'None', 11: 'Few Hours', 12: 'Good', 13: 'Satisfied' } },
      fnb_outlets: { avg: 3.4, answers: { 1: 'Excellent', 2: 'Good', 3: 'Fast', 4: 'Excellent', 5: 'Good', 6: 'Excellent', 7: 'Good', 8: 'Good', 9: 'Yes', 10: 'Good', 11: 'Average', 12: 'Good', 13: 'Perfect', 14: 'Satisfied' } },
      kitchen: { avg: 3.3, answers: { 1: 'Good', 2: 'Excellent', 3: 'Good', 4: 'Good', 5: 'Average', 6: 'Good', 7: 'Good' } },
      facilities: { avg: 3.1, answers: { 1: 'Good', 2: 'Average', 3: 'Good', 4: 'Good', 5: 'Good', 6: 'Good', 7: 'Excellent', 8: 'Easy', 9: 'Average', 10: 'Good', 11: 'Satisfied' } },
      pool_gym: { avg: 3.0, answers: { 1: 'Both', 2: 'Occasionally', 3: 'Good', 4: 'Average', 5: 'Mostly Available', 6: 'Good', 7: 'Average', 8: 'Good', 9: 'Average', 10: 'Satisfied', 11: 'Equipment' } },
      special_assistance: { avg: 2.8, answers: { 1: 'Yes', 2: 'Luggage assistance', 3: 'Available with Delay', 4: 'Good', 5: 'Moderately Trained', 6: 'Average', 7: 'Easy', 8: 'Satisfied', 9: 'Faster response' } },
    },
  },
  {
    id: 'resp-002', bill_number: 'BILL-2026-010', customer_name: 'Ananya Gupta', guest_type: 'Restaurant/Dining Guest', visit_purpose: 'Dining Only', stay_duration: 'Few Hours', submitted_at: '2026-04-12T19:15:00Z', services: ['fnb_outlets', 'kitchen'],
    answers: {
      fnb_outlets: { avg: 2.6, answers: { 1: 'Average', 2: 'Good', 3: 'Average', 4: 'Good', 5: 'Average', 6: 'Average', 7: 'Good', 8: 'Average', 9: 'No', 10: 'Average', 11: 'Average', 12: 'Average', 13: 'Acceptable', 14: 'Neutral' } },
      kitchen: { avg: 2.7, answers: { 1: 'Average', 2: 'Good', 3: 'Good', 4: 'Average', 5: 'Average', 6: 'Average', 7: 'Average' } },
    },
  },
  {
    id: 'resp-003', bill_number: 'BILL-2026-011', customer_name: 'Rajesh Kumar', guest_type: 'Banquet/Event Guest', visit_purpose: 'Event/Function', stay_duration: 'Few Hours', submitted_at: '2026-04-11T22:00:00Z', services: ['banquet_events'],
    answers: {
      banquet_events: { avg: 3.5, answers: { 1: 'Wedding', 2: 'Excellent', 3: 'Good', 4: 'Excellent', 5: 'Good', 6: 'Fast', 7: 'Excellent', 8: 'Good', 9: 'Excellent', 10: 'Good', 11: 'Good', 12: 'Very Satisfied' } },
    },
  },
  {
    id: 'resp-004', bill_number: 'BILL-2026-012', customer_name: 'Meera Nair', guest_type: 'Staying Guest', visit_purpose: 'Business', stay_duration: '2–3 Days', submitted_at: '2026-04-10T11:00:00Z', services: ['front_office', 'housekeeping', 'fnb_outlets', 'kitchen', 'facilities'],
    answers: {
      front_office: { avg: 3.8, answers: { 1: 'Very Smooth', 2: 'Very Short', 3: 'Excellent', 4: 'Yes', 5: 'Excellent', 6: 'Excellent', 7: 'Fully Resolved', 8: 'Good', 9: 'Very Clear', 10: 'Very Fast', 11: 'Very Satisfied' } },
      housekeeping: { avg: 3.7, answers: { 1: 'Excellent', 2: 'Excellent', 3: 'Good', 4: 'Very Fresh', 5: 'Fully Available', 6: 'Excellent', 7: 'Good', 8: 'Very Fast', 9: 'Very Satisfactory', 10: 'None', 11: 'Immediately', 12: 'Excellent', 13: 'Very Satisfied' } },
      fnb_outlets: { avg: 3.5, answers: { 1: 'Excellent', 2: 'Excellent', 3: 'Fast', 4: 'Excellent', 5: 'Good', 6: 'Good', 7: 'Excellent', 8: 'Good', 9: 'No', 10: 'Good', 11: 'Fast', 12: 'Good', 13: 'Perfect', 14: 'Very Satisfied' } },
      kitchen: { avg: 3.6, answers: { 1: 'Excellent', 2: 'Excellent', 3: 'Good', 4: 'Good', 5: 'Good', 6: 'Good', 7: 'Excellent' } },
      facilities: { avg: 3.4, answers: { 1: 'Good', 2: 'Good', 3: 'Excellent', 4: 'Good', 5: 'Good', 6: 'Good', 7: 'Excellent', 8: 'Very Easy', 9: 'Good', 10: 'Good', 11: 'Satisfied' } },
    },
  },
  {
    id: 'resp-005', bill_number: 'BILL-2026-013', customer_name: 'Karan Mehta', guest_type: 'Pool/Gym Member', visit_purpose: 'Leisure', stay_duration: 'Few Hours', submitted_at: '2026-04-09T08:30:00Z', services: ['pool_gym'],
    answers: {
      pool_gym: { avg: 3.2, answers: { 1: 'Gym', 2: 'Daily', 3: 'Good', 4: 'Good', 5: 'Always Available', 6: 'Good', 7: 'Good', 8: 'Excellent', 9: 'Average', 10: 'Satisfied', 11: 'Cleanliness' } },
    },
  },
];
